FROM golang:alpine
RUN apk add --no-cache curl postgresql-client
WORKDIR /zero


COPY . .
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
RUN go mod tidy
RUN go run . artisan key:generate
RUN go run . artisan jwt:secret
#RUN go build --ldflags "-extldflags -static" -o hero .
ENTRYPOINT ["air"]
#ENTRYPOINT ["/zero/hero"]